### ISSUE TITLE
Please can you provide a PRONTOQA dataset after the bugfix? 

### ISSUE THREAD

**Issue by alybel** [asaparov/prontoqa#6]
Dear Abulhair, 

firstly, thank you very much for your fantastic work on providing these datasets to the scientific world. I hear the regularly discussed, which shows they provide great value. Could you provide a dataset for download after the bugfix? This would be super helpful. Thank you so much! A

**Comment by asaparov** [comment]
Hello,
Thank you for your interest in this work! Sorry I didn't have time to address your issue until now, but I just updated the repo with the regenerated data which should include all bugfixes so far.

**Comment by alybel** [comment]
Dear Abulhair,

thank you so very much! Your work is highly appreciated because it provides a way to nicely investigate the reasoning capabilities with LLMs. Also, I am using SBERT as a means to compare semantical similarity between answers and hope to find ways to optimize an LLMs reasoning capability.

All the best,
Alexander

Von: Abulhair Saparov ***@***.***>
Datum: Donnerstag, 17. Oktober 2024 um 07:36
An: asaparov/prontoqa ***@***.***>
Cc: Alex ***@***.***>, Author ***@***.***>
Betreff: Re: [asaparov/prontoqa] Please can you provide a PRONTOQA dataset after the bugfix? (Issue #6)

Hello,
Thank you for your interest in this work! Sorry I didn't have time to address your issue until now, but I just updated the repo with the regenerated data which should include all bugfixes so far.
